const roles={general:'Eres Nexus: directo, preciso, honesto y práctico. No inventes datos.',architect:'Eres el arquitecto de Nexus. Divide problemas en capas, dependencias, riesgos y pruebas verificables.',coder:'Eres ingeniero senior. Prioriza seguridad, mantenibilidad y pruebas.',analyst:'Eres analista técnico. Separa hechos, supuestos, incertidumbres y riesgos.',critic:'Eres el crítico. Busca fallos, supuestos débiles y puntos únicos de fallo.'};
const env=(k)=>process.env[k]||'';
async function json(r,b,s=200){r.status(s).json(b)}async function llm(provider,model,system,prompt){let key=env(provider==='gemini'?'NEXUS_GEMINI_API_KEY':provider==='groq'?'NEXUS_GROQ_API_KEY':provider==='mistral'?'NEXUS_MISTRAL_API_KEY':provider==='kimi'?'NEXUS_KIMI_API_KEY':'NEXUS_OPENAI_API_KEY');if(!key)throw Error('Falta la clave de '+provider+'.');if(provider==='gemini'){const u='https://generativelanguage.googleapis.com/v1beta/models/'+encodeURIComponent(model)+':generateContent';const r=await fetch(u,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents:[{role:'user',parts:[{text:prompt}]}]})});const t=await r.text();if(!r.ok)throw Error('Gemini HTTP '+r.status);const d=JSON.parse(t);return d.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||''}
const u=provider==='openai'?'https://api.openai.com/v1/responses':provider==='groq'?'https://api.groq.com/openai/v1/chat/completions':provider==='mistral'?'https://api.mistral.ai/v1/chat/completions':'https://api.moonshot.ai/v1/chat/completions';const body=provider==='openai'?{model,instructions:system,input:prompt}:{model,messages:[{role:'system',content:system},{role:'user',content:prompt}]};const r=await fetch(u,{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify(body)});const t=await r.text();if(!r.ok)throw Error(provider+' HTTP '+r.status);const d=JSON.parse(t);return provider==='openai'?(d.output_text||''):(d.choices?.[0]?.message?.content||'')}
async function tavily(q){const key=env('TAVILY_API_KEY');if(!key)throw Error('Falta TAVILY_API_KEY.');const r=await fetch('https://api.tavily.com/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({api_key:key,query:q,search_depth:'advanced',max_results:8,include_answer:true})});const t=await r.text();if(!r.ok)throw Error('Tavily HTTP '+r.status);const d=JSON.parse(t);return(d.results||[]).map(x=>({title:x.title,url:x.url,content:x.content,score:x.score}))}
async function scrape(url){const r=await fetch(url,{headers:{'user-agent':'Nexus/1.0'}});const t=await r.text();const title=(t.match(/<title[^>]*>([\\s\\S]*?)<\\/title>/i)?.[1]||url).replace(/<[^>]+>/g,'').trim();const text=t.replace(/<script[\\s\\S]*?<\\/script>/gi,' ').replace(/<style[\\s\\S]*?<\\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\\s+/g,' ').trim();return{title,text:text.slice(0,30000),status:r.status}}
export default async function handler(req,res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type');if(req.method==='OPTIONS')return res.status(204).end();const u=new URL(req.url,'https://nexus.local'),p=u.pathname;try{
if(req.method==='GET'&&p==='/api/status')return json(res,{status:'ready',providers:{core:!!env('NEXUS_OPENAI_API_KEY'),openai:!!env('NEXUS_OPENAI_API_KEY'),groq:!!env('NEXUS_GROQ_API_KEY'),mistral:!!env('NEXUS_MISTRAL_API_KEY'),kimi:!!env('NEXUS_KIMI_API_KEY'),gemini:!!env('NEXUS_GEMINI_API_KEY'),tavily:!!env('TAVILY_API_KEY')}});
if(req.method==='POST'&&p==='/api/chat'){const b=req.body||{},prompt=String(b.prompt||'').trim();if(!prompt)return json(res,{error:'prompt is required'},400);const provider=b.provider==='core'?'openai':b.provider||'openai';const text=await llm(provider,b.model||'gpt-5',roles[b.role||'general']+(b.webContext?'\\n\\nContexto web: '+String(b.webContext).slice(0,18000):''),prompt);return json(res,{text,provider:b.provider||'core',model:b.model||'gpt-5'})}
if(req.method==='POST'&&p==='/api/web-search'){const q=String((req.body||{}).query||'').trim();if(!q)return json(res,{error:'query is required'},400);return json(res,{results:await tavily(q)})}
if(req.method==='POST'&&p==='/api/team'){const b=req.body||{},prompt=String(b.prompt||'').trim(),ctx=String(b.webContext||'').slice(0,16000);const [architect,researcher,critic]=await Promise.all([llm('openai','gpt-5',roles.architect,prompt+'\\n'+ctx),llm('openai','gpt-5',roles.analyst,prompt+'\\n'+ctx),llm('openai','gpt-5',roles.critic,prompt+'\\n'+ctx)]);const final=await llm('openai','gpt-5','Eres el coordinador final de Nexus. No ocultes contradicciones ni inventes datos.','Integra estos informes y responde de forma práctica.\\nARQUITECTO:\\n'+architect+'\\nINVESTIGADOR:\\n'+researcher+'\\nCRÍTICO:\\n'+critic+'\\nPREGUNTA:\\n'+prompt);return json(res,{architect,researcher,critic,final})}
if(req.method==='POST'&&p==='/api/scrape'){const url=String((req.body||{}).url||'').trim();if(!/^https?:\\/\\//i.test(url))return json(res,{error:'URL inválida'},400);return json(res,await scrape(url))}
if(req.method==='GET'&&p==='/api/mcp/servers'){const q=u.searchParams.get('search')||'';const r=await fetch('https://registry.modelcontextprotocol.io/v0.1/servers?limit=20&version=latest'+(q?'&search='+encodeURIComponent(q):''));const d=await r.json();if(!r.ok)return json(res,{error:'MCP registry HTTP '+r.status},502);return json(res,{servers:d.servers||[],metadata:d.metadata||{}})}
if(req.method==='GET'&&p==='/api/_healthcheck')return json(res,{ok:true,service:'nexus'});
return json(res,{error:'Not found'},404)}catch(e){return json(res,{error:e instanceof Error?e.message:'Server error'},500)}}